#!/bin/sh
# Copyright 2012 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

STASH_NAME="pre-commit-$(date +%s)"
git stash save -q --keep-index $STASH_NAME

./run-tests.sh
RESULT=$?

git stash pop -q

[ $RESULT -ne 0 ] && exit 1
exit 0
