// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: AudioMessage)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput AudioMessage
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"
	time "time"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockAudioMessage is a mock of AudioMessage interface.
type MockAudioMessage struct {
	ctrl     *gomock.Controller
	recorder *MockAudioMessageMockRecorder
	isgomock struct{}
}

// MockAudioMessageMockRecorder is the mock recorder for MockAudioMessage.
type MockAudioMessageMockRecorder struct {
	mock *MockAudioMessage
}

// NewMockAudioMessage creates a new mock instance.
func NewMockAudioMessage(ctrl *gomock.Controller) *MockAudioMessage {
	mock := &MockAudioMessage{ctrl: ctrl}
	mock.recorder = &MockAudioMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudioMessage) EXPECT() *MockAudioMessageMockRecorder {
	return m.recorder
}

// BotChatID mocks base method.
func (m *MockAudioMessage) BotChatID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotChatID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BotChatID indicates an expected call of BotChatID.
func (mr *MockAudioMessageMockRecorder) BotChatID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotChatID", reflect.TypeOf((*MockAudioMessage)(nil).BotChatID))
}

// Chat mocks base method.
func (m *MockAudioMessage) Chat() botinput.Chat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat")
	ret0, _ := ret[0].(botinput.Chat)
	return ret0
}

// Chat indicates an expected call of Chat.
func (mr *MockAudioMessageMockRecorder) Chat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockAudioMessage)(nil).Chat))
}

// GetRecipient mocks base method.
func (m *MockAudioMessage) GetRecipient() botinput.Recipient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipient")
	ret0, _ := ret[0].(botinput.Recipient)
	return ret0
}

// GetRecipient indicates an expected call of GetRecipient.
func (mr *MockAudioMessageMockRecorder) GetRecipient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipient", reflect.TypeOf((*MockAudioMessage)(nil).GetRecipient))
}

// GetSender mocks base method.
func (m *MockAudioMessage) GetSender() botinput.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSender")
	ret0, _ := ret[0].(botinput.User)
	return ret0
}

// GetSender indicates an expected call of GetSender.
func (mr *MockAudioMessageMockRecorder) GetSender() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSender", reflect.TypeOf((*MockAudioMessage)(nil).GetSender))
}

// GetTime mocks base method.
func (m *MockAudioMessage) GetTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetTime indicates an expected call of GetTime.
func (mr *MockAudioMessageMockRecorder) GetTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTime", reflect.TypeOf((*MockAudioMessage)(nil).GetTime))
}

// InputType mocks base method.
func (m *MockAudioMessage) InputType() botinput.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputType")
	ret0, _ := ret[0].(botinput.Type)
	return ret0
}

// InputType indicates an expected call of InputType.
func (mr *MockAudioMessageMockRecorder) InputType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputType", reflect.TypeOf((*MockAudioMessage)(nil).InputType))
}

// LogRequest mocks base method.
func (m *MockAudioMessage) LogRequest() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogRequest")
}

// LogRequest indicates an expected call of LogRequest.
func (mr *MockAudioMessageMockRecorder) LogRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogRequest", reflect.TypeOf((*MockAudioMessage)(nil).LogRequest))
}

// MessageIntID mocks base method.
func (m *MockAudioMessage) MessageIntID() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageIntID")
	ret0, _ := ret[0].(int)
	return ret0
}

// MessageIntID indicates an expected call of MessageIntID.
func (mr *MockAudioMessageMockRecorder) MessageIntID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageIntID", reflect.TypeOf((*MockAudioMessage)(nil).MessageIntID))
}

// MessageStringID mocks base method.
func (m *MockAudioMessage) MessageStringID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageStringID")
	ret0, _ := ret[0].(string)
	return ret0
}

// MessageStringID indicates an expected call of MessageStringID.
func (mr *MockAudioMessageMockRecorder) MessageStringID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageStringID", reflect.TypeOf((*MockAudioMessage)(nil).MessageStringID))
}
