// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: CallbackQuery)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput CallbackQuery
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockCallbackQuery is a mock of CallbackQuery interface.
type MockCallbackQuery struct {
	ctrl     *gomock.Controller
	recorder *MockCallbackQueryMockRecorder
	isgomock struct{}
}

// MockCallbackQueryMockRecorder is the mock recorder for MockCallbackQuery.
type MockCallbackQueryMockRecorder struct {
	mock *MockCallbackQuery
}

// NewMockCallbackQuery creates a new mock instance.
func NewMockCallbackQuery(ctrl *gomock.Controller) *MockCallbackQuery {
	mock := &MockCallbackQuery{ctrl: ctrl}
	mock.recorder = &MockCallbackQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCallbackQuery) EXPECT() *MockCallbackQueryMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockCallbackQuery) Chat() botinput.Chat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat")
	ret0, _ := ret[0].(botinput.Chat)
	return ret0
}

// Chat indicates an expected call of Chat.
func (mr *MockCallbackQueryMockRecorder) Chat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockCallbackQuery)(nil).Chat))
}

// GetData mocks base method.
func (m *MockCallbackQuery) GetData() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetData")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetData indicates an expected call of GetData.
func (mr *MockCallbackQueryMockRecorder) GetData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetData", reflect.TypeOf((*MockCallbackQuery)(nil).GetData))
}

// GetFrom mocks base method.
func (m *MockCallbackQuery) GetFrom() botinput.Sender {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFrom")
	ret0, _ := ret[0].(botinput.Sender)
	return ret0
}

// GetFrom indicates an expected call of GetFrom.
func (mr *MockCallbackQueryMockRecorder) GetFrom() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFrom", reflect.TypeOf((*MockCallbackQuery)(nil).GetFrom))
}

// GetID mocks base method.
func (m *MockCallbackQuery) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockCallbackQueryMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockCallbackQuery)(nil).GetID))
}

// GetMessage mocks base method.
func (m *MockCallbackQuery) GetMessage() botinput.Message {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage")
	ret0, _ := ret[0].(botinput.Message)
	return ret0
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockCallbackQueryMockRecorder) GetMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockCallbackQuery)(nil).GetMessage))
}
