// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: InputMessage)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput InputMessage
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"
	time "time"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockInputMessage is a mock of InputMessage interface.
type MockInputMessage struct {
	ctrl     *gomock.Controller
	recorder *MockInputMessageMockRecorder
	isgomock struct{}
}

// MockInputMessageMockRecorder is the mock recorder for MockInputMessage.
type MockInputMessageMockRecorder struct {
	mock *MockInputMessage
}

// NewMockInputMessage creates a new mock instance.
func NewMockInputMessage(ctrl *gomock.Controller) *MockInputMessage {
	mock := &MockInputMessage{ctrl: ctrl}
	mock.recorder = &MockInputMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInputMessage) EXPECT() *MockInputMessageMockRecorder {
	return m.recorder
}

// BotChatID mocks base method.
func (m *MockInputMessage) BotChatID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotChatID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BotChatID indicates an expected call of BotChatID.
func (mr *MockInputMessageMockRecorder) BotChatID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotChatID", reflect.TypeOf((*MockInputMessage)(nil).BotChatID))
}

// Chat mocks base method.
func (m *MockInputMessage) Chat() botinput.Chat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat")
	ret0, _ := ret[0].(botinput.Chat)
	return ret0
}

// Chat indicates an expected call of Chat.
func (mr *MockInputMessageMockRecorder) Chat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockInputMessage)(nil).Chat))
}

// GetRecipient mocks base method.
func (m *MockInputMessage) GetRecipient() botinput.Recipient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipient")
	ret0, _ := ret[0].(botinput.Recipient)
	return ret0
}

// GetRecipient indicates an expected call of GetRecipient.
func (mr *MockInputMessageMockRecorder) GetRecipient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipient", reflect.TypeOf((*MockInputMessage)(nil).GetRecipient))
}

// GetSender mocks base method.
func (m *MockInputMessage) GetSender() botinput.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSender")
	ret0, _ := ret[0].(botinput.User)
	return ret0
}

// GetSender indicates an expected call of GetSender.
func (mr *MockInputMessageMockRecorder) GetSender() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSender", reflect.TypeOf((*MockInputMessage)(nil).GetSender))
}

// GetTime mocks base method.
func (m *MockInputMessage) GetTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetTime indicates an expected call of GetTime.
func (mr *MockInputMessageMockRecorder) GetTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTime", reflect.TypeOf((*MockInputMessage)(nil).GetTime))
}

// InputType mocks base method.
func (m *MockInputMessage) InputType() botinput.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputType")
	ret0, _ := ret[0].(botinput.Type)
	return ret0
}

// InputType indicates an expected call of InputType.
func (mr *MockInputMessageMockRecorder) InputType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputType", reflect.TypeOf((*MockInputMessage)(nil).InputType))
}

// LogRequest mocks base method.
func (m *MockInputMessage) LogRequest() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogRequest")
}

// LogRequest indicates an expected call of LogRequest.
func (mr *MockInputMessageMockRecorder) LogRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogRequest", reflect.TypeOf((*MockInputMessage)(nil).LogRequest))
}

// MessageIntID mocks base method.
func (m *MockInputMessage) MessageIntID() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageIntID")
	ret0, _ := ret[0].(int)
	return ret0
}

// MessageIntID indicates an expected call of MessageIntID.
func (mr *MockInputMessageMockRecorder) MessageIntID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageIntID", reflect.TypeOf((*MockInputMessage)(nil).MessageIntID))
}

// MessageStringID mocks base method.
func (m *MockInputMessage) MessageStringID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageStringID")
	ret0, _ := ret[0].(string)
	return ret0
}

// MessageStringID indicates an expected call of MessageStringID.
func (mr *MockInputMessageMockRecorder) MessageStringID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageStringID", reflect.TypeOf((*MockInputMessage)(nil).MessageStringID))
}
