// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: LocationMessage)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput LocationMessage
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"
	time "time"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockLocationMessage is a mock of LocationMessage interface.
type MockLocationMessage struct {
	ctrl     *gomock.Controller
	recorder *MockLocationMessageMockRecorder
	isgomock struct{}
}

// MockLocationMessageMockRecorder is the mock recorder for MockLocationMessage.
type MockLocationMessageMockRecorder struct {
	mock *MockLocationMessage
}

// NewMockLocationMessage creates a new mock instance.
func NewMockLocationMessage(ctrl *gomock.Controller) *MockLocationMessage {
	mock := &MockLocationMessage{ctrl: ctrl}
	mock.recorder = &MockLocationMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocationMessage) EXPECT() *MockLocationMessageMockRecorder {
	return m.recorder
}

// BotChatID mocks base method.
func (m *MockLocationMessage) BotChatID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotChatID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BotChatID indicates an expected call of BotChatID.
func (mr *MockLocationMessageMockRecorder) BotChatID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotChatID", reflect.TypeOf((*MockLocationMessage)(nil).BotChatID))
}

// Chat mocks base method.
func (m *MockLocationMessage) Chat() botinput.Chat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat")
	ret0, _ := ret[0].(botinput.Chat)
	return ret0
}

// Chat indicates an expected call of Chat.
func (mr *MockLocationMessageMockRecorder) Chat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockLocationMessage)(nil).Chat))
}

// GetLatitude mocks base method.
func (m *MockLocationMessage) GetLatitude() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatitude")
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetLatitude indicates an expected call of GetLatitude.
func (mr *MockLocationMessageMockRecorder) GetLatitude() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatitude", reflect.TypeOf((*MockLocationMessage)(nil).GetLatitude))
}

// GetLongitude mocks base method.
func (m *MockLocationMessage) GetLongitude() float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLongitude")
	ret0, _ := ret[0].(float64)
	return ret0
}

// GetLongitude indicates an expected call of GetLongitude.
func (mr *MockLocationMessageMockRecorder) GetLongitude() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLongitude", reflect.TypeOf((*MockLocationMessage)(nil).GetLongitude))
}

// GetRecipient mocks base method.
func (m *MockLocationMessage) GetRecipient() botinput.Recipient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipient")
	ret0, _ := ret[0].(botinput.Recipient)
	return ret0
}

// GetRecipient indicates an expected call of GetRecipient.
func (mr *MockLocationMessageMockRecorder) GetRecipient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipient", reflect.TypeOf((*MockLocationMessage)(nil).GetRecipient))
}

// GetSender mocks base method.
func (m *MockLocationMessage) GetSender() botinput.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSender")
	ret0, _ := ret[0].(botinput.User)
	return ret0
}

// GetSender indicates an expected call of GetSender.
func (mr *MockLocationMessageMockRecorder) GetSender() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSender", reflect.TypeOf((*MockLocationMessage)(nil).GetSender))
}

// GetTime mocks base method.
func (m *MockLocationMessage) GetTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetTime indicates an expected call of GetTime.
func (mr *MockLocationMessageMockRecorder) GetTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTime", reflect.TypeOf((*MockLocationMessage)(nil).GetTime))
}

// InputType mocks base method.
func (m *MockLocationMessage) InputType() botinput.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputType")
	ret0, _ := ret[0].(botinput.Type)
	return ret0
}

// InputType indicates an expected call of InputType.
func (mr *MockLocationMessageMockRecorder) InputType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputType", reflect.TypeOf((*MockLocationMessage)(nil).InputType))
}

// LogRequest mocks base method.
func (m *MockLocationMessage) LogRequest() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogRequest")
}

// LogRequest indicates an expected call of LogRequest.
func (mr *MockLocationMessageMockRecorder) LogRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogRequest", reflect.TypeOf((*MockLocationMessage)(nil).LogRequest))
}

// MessageIntID mocks base method.
func (m *MockLocationMessage) MessageIntID() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageIntID")
	ret0, _ := ret[0].(int)
	return ret0
}

// MessageIntID indicates an expected call of MessageIntID.
func (mr *MockLocationMessageMockRecorder) MessageIntID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageIntID", reflect.TypeOf((*MockLocationMessage)(nil).MessageIntID))
}

// MessageStringID mocks base method.
func (m *MockLocationMessage) MessageStringID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageStringID")
	ret0, _ := ret[0].(string)
	return ret0
}

// MessageStringID indicates an expected call of MessageStringID.
func (mr *MockLocationMessageMockRecorder) MessageStringID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageStringID", reflect.TypeOf((*MockLocationMessage)(nil).MessageStringID))
}
