// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: Postback)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput Postback
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPostback is a mock of Postback interface.
type MockPostback struct {
	ctrl     *gomock.Controller
	recorder *MockPostbackMockRecorder
	isgomock struct{}
}

// MockPostbackMockRecorder is the mock recorder for MockPostback.
type MockPostbackMockRecorder struct {
	mock *MockPostback
}

// NewMockPostback creates a new mock instance.
func NewMockPostback(ctrl *gomock.Controller) *MockPostback {
	mock := &MockPostback{ctrl: ctrl}
	mock.recorder = &MockPostbackMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostback) EXPECT() *MockPostbackMockRecorder {
	return m.recorder
}

// Payload mocks base method.
func (m *MockPostback) Payload() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Payload")
	ret0, _ := ret[0].(string)
	return ret0
}

// Payload indicates an expected call of Payload.
func (mr *MockPostbackMockRecorder) Payload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Payload", reflect.TypeOf((*MockPostback)(nil).Payload))
}

// PostbackMessage mocks base method.
func (m *MockPostback) PostbackMessage() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostbackMessage")
	ret0, _ := ret[0].(any)
	return ret0
}

// PostbackMessage indicates an expected call of PostbackMessage.
func (mr *MockPostbackMockRecorder) PostbackMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostbackMessage", reflect.TypeOf((*MockPostback)(nil).PostbackMessage))
}
