// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: PreCheckoutQuery)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput PreCheckoutQuery
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockPreCheckoutQuery is a mock of PreCheckoutQuery interface.
type MockPreCheckoutQuery struct {
	ctrl     *gomock.Controller
	recorder *MockPreCheckoutQueryMockRecorder
	isgomock struct{}
}

// MockPreCheckoutQueryMockRecorder is the mock recorder for MockPreCheckoutQuery.
type MockPreCheckoutQueryMockRecorder struct {
	mock *MockPreCheckoutQuery
}

// NewMockPreCheckoutQuery creates a new mock instance.
func NewMockPreCheckoutQuery(ctrl *gomock.Controller) *MockPreCheckoutQuery {
	mock := &MockPreCheckoutQuery{ctrl: ctrl}
	mock.recorder = &MockPreCheckoutQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreCheckoutQuery) EXPECT() *MockPreCheckoutQueryMockRecorder {
	return m.recorder
}

// GetCurrency mocks base method.
func (m *MockPreCheckoutQuery) GetCurrency() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrency")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCurrency indicates an expected call of GetCurrency.
func (mr *MockPreCheckoutQueryMockRecorder) GetCurrency() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrency", reflect.TypeOf((*MockPreCheckoutQuery)(nil).GetCurrency))
}

// GetFrom mocks base method.
func (m *MockPreCheckoutQuery) GetFrom() botinput.Sender {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFrom")
	ret0, _ := ret[0].(botinput.Sender)
	return ret0
}

// GetFrom indicates an expected call of GetFrom.
func (mr *MockPreCheckoutQueryMockRecorder) GetFrom() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFrom", reflect.TypeOf((*MockPreCheckoutQuery)(nil).GetFrom))
}

// GetInvoicePayload mocks base method.
func (m *MockPreCheckoutQuery) GetInvoicePayload() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoicePayload")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetInvoicePayload indicates an expected call of GetInvoicePayload.
func (mr *MockPreCheckoutQueryMockRecorder) GetInvoicePayload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoicePayload", reflect.TypeOf((*MockPreCheckoutQuery)(nil).GetInvoicePayload))
}

// GetOrderInfo mocks base method.
func (m *MockPreCheckoutQuery) GetOrderInfo() botinput.OrderInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderInfo")
	ret0, _ := ret[0].(botinput.OrderInfo)
	return ret0
}

// GetOrderInfo indicates an expected call of GetOrderInfo.
func (mr *MockPreCheckoutQueryMockRecorder) GetOrderInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderInfo", reflect.TypeOf((*MockPreCheckoutQuery)(nil).GetOrderInfo))
}

// GetPreCheckoutQueryID mocks base method.
func (m *MockPreCheckoutQuery) GetPreCheckoutQueryID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreCheckoutQueryID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPreCheckoutQueryID indicates an expected call of GetPreCheckoutQueryID.
func (mr *MockPreCheckoutQueryMockRecorder) GetPreCheckoutQueryID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreCheckoutQueryID", reflect.TypeOf((*MockPreCheckoutQuery)(nil).GetPreCheckoutQueryID))
}

// GetShippingOptionID mocks base method.
func (m *MockPreCheckoutQuery) GetShippingOptionID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShippingOptionID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetShippingOptionID indicates an expected call of GetShippingOptionID.
func (mr *MockPreCheckoutQueryMockRecorder) GetShippingOptionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShippingOptionID", reflect.TypeOf((*MockPreCheckoutQuery)(nil).GetShippingOptionID))
}

// GetTotalAmount mocks base method.
func (m *MockPreCheckoutQuery) GetTotalAmount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAmount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetTotalAmount indicates an expected call of GetTotalAmount.
func (mr *MockPreCheckoutQueryMockRecorder) GetTotalAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAmount", reflect.TypeOf((*MockPreCheckoutQuery)(nil).GetTotalAmount))
}
