// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: RefundedPayment)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput RefundedPayment
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRefundedPayment is a mock of RefundedPayment interface.
type MockRefundedPayment struct {
	ctrl     *gomock.Controller
	recorder *MockRefundedPaymentMockRecorder
	isgomock struct{}
}

// MockRefundedPaymentMockRecorder is the mock recorder for MockRefundedPayment.
type MockRefundedPaymentMockRecorder struct {
	mock *MockRefundedPayment
}

// NewMockRefundedPayment creates a new mock instance.
func NewMockRefundedPayment(ctrl *gomock.Controller) *MockRefundedPayment {
	mock := &MockRefundedPayment{ctrl: ctrl}
	mock.recorder = &MockRefundedPaymentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefundedPayment) EXPECT() *MockRefundedPaymentMockRecorder {
	return m.recorder
}

// GetCurrency mocks base method.
func (m *MockRefundedPayment) GetCurrency() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrency")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCurrency indicates an expected call of GetCurrency.
func (mr *MockRefundedPaymentMockRecorder) GetCurrency() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrency", reflect.TypeOf((*MockRefundedPayment)(nil).GetCurrency))
}

// GetInvoicePayload mocks base method.
func (m *MockRefundedPayment) GetInvoicePayload() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoicePayload")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetInvoicePayload indicates an expected call of GetInvoicePayload.
func (mr *MockRefundedPaymentMockRecorder) GetInvoicePayload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoicePayload", reflect.TypeOf((*MockRefundedPayment)(nil).GetInvoicePayload))
}

// GetMessengerChargeID mocks base method.
func (m *MockRefundedPayment) GetMessengerChargeID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessengerChargeID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMessengerChargeID indicates an expected call of GetMessengerChargeID.
func (mr *MockRefundedPaymentMockRecorder) GetMessengerChargeID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessengerChargeID", reflect.TypeOf((*MockRefundedPayment)(nil).GetMessengerChargeID))
}

// GetPaymentProviderChargeID mocks base method.
func (m *MockRefundedPayment) GetPaymentProviderChargeID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentProviderChargeID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPaymentProviderChargeID indicates an expected call of GetPaymentProviderChargeID.
func (mr *MockRefundedPaymentMockRecorder) GetPaymentProviderChargeID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentProviderChargeID", reflect.TypeOf((*MockRefundedPayment)(nil).GetPaymentProviderChargeID))
}

// GetTotalAmount mocks base method.
func (m *MockRefundedPayment) GetTotalAmount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAmount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetTotalAmount indicates an expected call of GetTotalAmount.
func (mr *MockRefundedPaymentMockRecorder) GetTotalAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAmount", reflect.TypeOf((*MockRefundedPayment)(nil).GetTotalAmount))
}
