// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: StickerMessage)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput StickerMessage
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"
	time "time"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockStickerMessage is a mock of StickerMessage interface.
type MockStickerMessage struct {
	ctrl     *gomock.Controller
	recorder *MockStickerMessageMockRecorder
	isgomock struct{}
}

// MockStickerMessageMockRecorder is the mock recorder for MockStickerMessage.
type MockStickerMessageMockRecorder struct {
	mock *MockStickerMessage
}

// NewMockStickerMessage creates a new mock instance.
func NewMockStickerMessage(ctrl *gomock.Controller) *MockStickerMessage {
	mock := &MockStickerMessage{ctrl: ctrl}
	mock.recorder = &MockStickerMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStickerMessage) EXPECT() *MockStickerMessageMockRecorder {
	return m.recorder
}

// BotChatID mocks base method.
func (m *MockStickerMessage) BotChatID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotChatID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BotChatID indicates an expected call of BotChatID.
func (mr *MockStickerMessageMockRecorder) BotChatID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotChatID", reflect.TypeOf((*MockStickerMessage)(nil).BotChatID))
}

// Chat mocks base method.
func (m *MockStickerMessage) Chat() botinput.Chat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat")
	ret0, _ := ret[0].(botinput.Chat)
	return ret0
}

// Chat indicates an expected call of Chat.
func (mr *MockStickerMessageMockRecorder) Chat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockStickerMessage)(nil).Chat))
}

// GetRecipient mocks base method.
func (m *MockStickerMessage) GetRecipient() botinput.Recipient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipient")
	ret0, _ := ret[0].(botinput.Recipient)
	return ret0
}

// GetRecipient indicates an expected call of GetRecipient.
func (mr *MockStickerMessageMockRecorder) GetRecipient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipient", reflect.TypeOf((*MockStickerMessage)(nil).GetRecipient))
}

// GetSender mocks base method.
func (m *MockStickerMessage) GetSender() botinput.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSender")
	ret0, _ := ret[0].(botinput.User)
	return ret0
}

// GetSender indicates an expected call of GetSender.
func (mr *MockStickerMessageMockRecorder) GetSender() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSender", reflect.TypeOf((*MockStickerMessage)(nil).GetSender))
}

// GetTime mocks base method.
func (m *MockStickerMessage) GetTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetTime indicates an expected call of GetTime.
func (mr *MockStickerMessageMockRecorder) GetTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTime", reflect.TypeOf((*MockStickerMessage)(nil).GetTime))
}

// InputType mocks base method.
func (m *MockStickerMessage) InputType() botinput.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputType")
	ret0, _ := ret[0].(botinput.Type)
	return ret0
}

// InputType indicates an expected call of InputType.
func (mr *MockStickerMessageMockRecorder) InputType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputType", reflect.TypeOf((*MockStickerMessage)(nil).InputType))
}

// LogRequest mocks base method.
func (m *MockStickerMessage) LogRequest() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogRequest")
}

// LogRequest indicates an expected call of LogRequest.
func (mr *MockStickerMessageMockRecorder) LogRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogRequest", reflect.TypeOf((*MockStickerMessage)(nil).LogRequest))
}

// MessageIntID mocks base method.
func (m *MockStickerMessage) MessageIntID() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageIntID")
	ret0, _ := ret[0].(int)
	return ret0
}

// MessageIntID indicates an expected call of MessageIntID.
func (mr *MockStickerMessageMockRecorder) MessageIntID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageIntID", reflect.TypeOf((*MockStickerMessage)(nil).MessageIntID))
}

// MessageStringID mocks base method.
func (m *MockStickerMessage) MessageStringID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageStringID")
	ret0, _ := ret[0].(string)
	return ret0
}

// MessageStringID indicates an expected call of MessageStringID.
func (mr *MockStickerMessageMockRecorder) MessageStringID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageStringID", reflect.TypeOf((*MockStickerMessage)(nil).MessageStringID))
}
