// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: SuccessfulPayment)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput SuccessfulPayment
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"
	time "time"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockSuccessfulPayment is a mock of SuccessfulPayment interface.
type MockSuccessfulPayment struct {
	ctrl     *gomock.Controller
	recorder *MockSuccessfulPaymentMockRecorder
	isgomock struct{}
}

// MockSuccessfulPaymentMockRecorder is the mock recorder for MockSuccessfulPayment.
type MockSuccessfulPaymentMockRecorder struct {
	mock *MockSuccessfulPayment
}

// NewMockSuccessfulPayment creates a new mock instance.
func NewMockSuccessfulPayment(ctrl *gomock.Controller) *MockSuccessfulPayment {
	mock := &MockSuccessfulPayment{ctrl: ctrl}
	mock.recorder = &MockSuccessfulPaymentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuccessfulPayment) EXPECT() *MockSuccessfulPaymentMockRecorder {
	return m.recorder
}

// GetCurrency mocks base method.
func (m *MockSuccessfulPayment) GetCurrency() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrency")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCurrency indicates an expected call of GetCurrency.
func (mr *MockSuccessfulPaymentMockRecorder) GetCurrency() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrency", reflect.TypeOf((*MockSuccessfulPayment)(nil).GetCurrency))
}

// GetInvoicePayload mocks base method.
func (m *MockSuccessfulPayment) GetInvoicePayload() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInvoicePayload")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetInvoicePayload indicates an expected call of GetInvoicePayload.
func (mr *MockSuccessfulPaymentMockRecorder) GetInvoicePayload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInvoicePayload", reflect.TypeOf((*MockSuccessfulPayment)(nil).GetInvoicePayload))
}

// GetIsFirstRecurring mocks base method.
func (m *MockSuccessfulPayment) GetIsFirstRecurring() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIsFirstRecurring")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetIsFirstRecurring indicates an expected call of GetIsFirstRecurring.
func (mr *MockSuccessfulPaymentMockRecorder) GetIsFirstRecurring() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIsFirstRecurring", reflect.TypeOf((*MockSuccessfulPayment)(nil).GetIsFirstRecurring))
}

// GetIsRecurring mocks base method.
func (m *MockSuccessfulPayment) GetIsRecurring() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIsRecurring")
	ret0, _ := ret[0].(bool)
	return ret0
}

// GetIsRecurring indicates an expected call of GetIsRecurring.
func (mr *MockSuccessfulPaymentMockRecorder) GetIsRecurring() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIsRecurring", reflect.TypeOf((*MockSuccessfulPayment)(nil).GetIsRecurring))
}

// GetMessengerChargeID mocks base method.
func (m *MockSuccessfulPayment) GetMessengerChargeID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessengerChargeID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMessengerChargeID indicates an expected call of GetMessengerChargeID.
func (mr *MockSuccessfulPaymentMockRecorder) GetMessengerChargeID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessengerChargeID", reflect.TypeOf((*MockSuccessfulPayment)(nil).GetMessengerChargeID))
}

// GetOrderInfo mocks base method.
func (m *MockSuccessfulPayment) GetOrderInfo() botinput.OrderInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderInfo")
	ret0, _ := ret[0].(botinput.OrderInfo)
	return ret0
}

// GetOrderInfo indicates an expected call of GetOrderInfo.
func (mr *MockSuccessfulPaymentMockRecorder) GetOrderInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderInfo", reflect.TypeOf((*MockSuccessfulPayment)(nil).GetOrderInfo))
}

// GetPaymentProviderChargeID mocks base method.
func (m *MockSuccessfulPayment) GetPaymentProviderChargeID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentProviderChargeID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPaymentProviderChargeID indicates an expected call of GetPaymentProviderChargeID.
func (mr *MockSuccessfulPaymentMockRecorder) GetPaymentProviderChargeID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentProviderChargeID", reflect.TypeOf((*MockSuccessfulPayment)(nil).GetPaymentProviderChargeID))
}

// GetShippingOptionID mocks base method.
func (m *MockSuccessfulPayment) GetShippingOptionID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShippingOptionID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetShippingOptionID indicates an expected call of GetShippingOptionID.
func (mr *MockSuccessfulPaymentMockRecorder) GetShippingOptionID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShippingOptionID", reflect.TypeOf((*MockSuccessfulPayment)(nil).GetShippingOptionID))
}

// GetSubscriptionExpirationDate mocks base method.
func (m *MockSuccessfulPayment) GetSubscriptionExpirationDate() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionExpirationDate")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetSubscriptionExpirationDate indicates an expected call of GetSubscriptionExpirationDate.
func (mr *MockSuccessfulPaymentMockRecorder) GetSubscriptionExpirationDate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionExpirationDate", reflect.TypeOf((*MockSuccessfulPayment)(nil).GetSubscriptionExpirationDate))
}

// GetTotalAmount mocks base method.
func (m *MockSuccessfulPayment) GetTotalAmount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalAmount")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetTotalAmount indicates an expected call of GetTotalAmount.
func (mr *MockSuccessfulPaymentMockRecorder) GetTotalAmount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalAmount", reflect.TypeOf((*MockSuccessfulPayment)(nil).GetTotalAmount))
}
