// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: TextMessage)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput TextMessage
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"
	time "time"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockTextMessage is a mock of TextMessage interface.
type MockTextMessage struct {
	ctrl     *gomock.Controller
	recorder *MockTextMessageMockRecorder
	isgomock struct{}
}

// MockTextMessageMockRecorder is the mock recorder for MockTextMessage.
type MockTextMessageMockRecorder struct {
	mock *MockTextMessage
}

// NewMockTextMessage creates a new mock instance.
func NewMockTextMessage(ctrl *gomock.Controller) *MockTextMessage {
	mock := &MockTextMessage{ctrl: ctrl}
	mock.recorder = &MockTextMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTextMessage) EXPECT() *MockTextMessageMockRecorder {
	return m.recorder
}

// BotChatID mocks base method.
func (m *MockTextMessage) BotChatID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotChatID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BotChatID indicates an expected call of BotChatID.
func (mr *MockTextMessageMockRecorder) BotChatID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotChatID", reflect.TypeOf((*MockTextMessage)(nil).BotChatID))
}

// Chat mocks base method.
func (m *MockTextMessage) Chat() botinput.Chat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat")
	ret0, _ := ret[0].(botinput.Chat)
	return ret0
}

// Chat indicates an expected call of Chat.
func (mr *MockTextMessageMockRecorder) Chat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockTextMessage)(nil).Chat))
}

// GetRecipient mocks base method.
func (m *MockTextMessage) GetRecipient() botinput.Recipient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipient")
	ret0, _ := ret[0].(botinput.Recipient)
	return ret0
}

// GetRecipient indicates an expected call of GetRecipient.
func (mr *MockTextMessageMockRecorder) GetRecipient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipient", reflect.TypeOf((*MockTextMessage)(nil).GetRecipient))
}

// GetSender mocks base method.
func (m *MockTextMessage) GetSender() botinput.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSender")
	ret0, _ := ret[0].(botinput.User)
	return ret0
}

// GetSender indicates an expected call of GetSender.
func (mr *MockTextMessageMockRecorder) GetSender() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSender", reflect.TypeOf((*MockTextMessage)(nil).GetSender))
}

// GetTime mocks base method.
func (m *MockTextMessage) GetTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetTime indicates an expected call of GetTime.
func (mr *MockTextMessageMockRecorder) GetTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTime", reflect.TypeOf((*MockTextMessage)(nil).GetTime))
}

// InputType mocks base method.
func (m *MockTextMessage) InputType() botinput.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputType")
	ret0, _ := ret[0].(botinput.Type)
	return ret0
}

// InputType indicates an expected call of InputType.
func (mr *MockTextMessageMockRecorder) InputType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputType", reflect.TypeOf((*MockTextMessage)(nil).InputType))
}

// IntID mocks base method.
func (m *MockTextMessage) IntID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// IntID indicates an expected call of IntID.
func (mr *MockTextMessageMockRecorder) IntID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntID", reflect.TypeOf((*MockTextMessage)(nil).IntID))
}

// IsEdited mocks base method.
func (m *MockTextMessage) IsEdited() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsEdited")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsEdited indicates an expected call of IsEdited.
func (mr *MockTextMessageMockRecorder) IsEdited() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsEdited", reflect.TypeOf((*MockTextMessage)(nil).IsEdited))
}

// LogRequest mocks base method.
func (m *MockTextMessage) LogRequest() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogRequest")
}

// LogRequest indicates an expected call of LogRequest.
func (mr *MockTextMessageMockRecorder) LogRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogRequest", reflect.TypeOf((*MockTextMessage)(nil).LogRequest))
}

// StringID mocks base method.
func (m *MockTextMessage) StringID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringID")
	ret0, _ := ret[0].(string)
	return ret0
}

// StringID indicates an expected call of StringID.
func (mr *MockTextMessageMockRecorder) StringID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringID", reflect.TypeOf((*MockTextMessage)(nil).StringID))
}

// Text mocks base method.
func (m *MockTextMessage) Text() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Text")
	ret0, _ := ret[0].(string)
	return ret0
}

// Text indicates an expected call of Text.
func (mr *MockTextMessageMockRecorder) Text() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Text", reflect.TypeOf((*MockTextMessage)(nil).Text))
}
