// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: Unsubscribed)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput Unsubscribed
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUnsubscribed is a mock of Unsubscribed interface.
type MockUnsubscribed struct {
	ctrl     *gomock.Controller
	recorder *MockUnsubscribedMockRecorder
	isgomock struct{}
}

// MockUnsubscribedMockRecorder is the mock recorder for MockUnsubscribed.
type MockUnsubscribedMockRecorder struct {
	mock *MockUnsubscribed
}

// NewMockUnsubscribed creates a new mock instance.
func NewMockUnsubscribed(ctrl *gomock.Controller) *MockUnsubscribed {
	mock := &MockUnsubscribed{ctrl: ctrl}
	mock.recorder = &MockUnsubscribedMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsubscribed) EXPECT() *MockUnsubscribedMockRecorder {
	return m.recorder
}

// UnsubscribedMessage mocks base method.
func (m *MockUnsubscribed) UnsubscribedMessage() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnsubscribedMessage")
	ret0, _ := ret[0].(any)
	return ret0
}

// UnsubscribedMessage indicates an expected call of UnsubscribedMessage.
func (mr *MockUnsubscribedMockRecorder) UnsubscribedMessage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnsubscribedMessage", reflect.TypeOf((*MockUnsubscribed)(nil).UnsubscribedMessage))
}
