// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: NewChatMembersMessage)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput NewChatMembersMessage
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockNewChatMembersMessage is a mock of NewChatMembersMessage interface.
type MockNewChatMembersMessage struct {
	ctrl     *gomock.Controller
	recorder *MockNewChatMembersMessageMockRecorder
	isgomock struct{}
}

// MockNewChatMembersMessageMockRecorder is the mock recorder for MockNewChatMembersMessage.
type MockNewChatMembersMessageMockRecorder struct {
	mock *MockNewChatMembersMessage
}

// NewMockNewChatMembersMessage creates a new mock instance.
func NewMockNewChatMembersMessage(ctrl *gomock.Controller) *MockNewChatMembersMessage {
	mock := &MockNewChatMembersMessage{ctrl: ctrl}
	mock.recorder = &MockNewChatMembersMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNewChatMembersMessage) EXPECT() *MockNewChatMembersMessageMockRecorder {
	return m.recorder
}

// BotChatID mocks base method.
func (m *MockNewChatMembersMessage) BotChatID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotChatID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BotChatID indicates an expected call of BotChatID.
func (mr *MockNewChatMembersMessageMockRecorder) BotChatID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotChatID", reflect.TypeOf((*MockNewChatMembersMessage)(nil).BotChatID))
}

// NewChatMembers mocks base method.
func (m *MockNewChatMembersMessage) NewChatMembers() []botinput.Actor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewChatMembers")
	ret0, _ := ret[0].([]botinput.Actor)
	return ret0
}

// NewChatMembers indicates an expected call of NewChatMembers.
func (mr *MockNewChatMembersMessageMockRecorder) NewChatMembers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewChatMembers", reflect.TypeOf((*MockNewChatMembersMessage)(nil).NewChatMembers))
}
