// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: LeftChatMembersMessage)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput LeftChatMembersMessage
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockLeftChatMembersMessage is a mock of LeftChatMembersMessage interface.
type MockLeftChatMembersMessage struct {
	ctrl     *gomock.Controller
	recorder *MockLeftChatMembersMessageMockRecorder
	isgomock struct{}
}

// MockLeftChatMembersMessageMockRecorder is the mock recorder for MockLeftChatMembersMessage.
type MockLeftChatMembersMessageMockRecorder struct {
	mock *MockLeftChatMembersMessage
}

// NewMockLeftChatMembersMessage creates a new mock instance.
func NewMockLeftChatMembersMessage(ctrl *gomock.Controller) *MockLeftChatMembersMessage {
	mock := &MockLeftChatMembersMessage{ctrl: ctrl}
	mock.recorder = &MockLeftChatMembersMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLeftChatMembersMessage) EXPECT() *MockLeftChatMembersMessageMockRecorder {
	return m.recorder
}

// BotChatID mocks base method.
func (m *MockLeftChatMembersMessage) BotChatID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotChatID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BotChatID indicates an expected call of BotChatID.
func (mr *MockLeftChatMembersMessageMockRecorder) BotChatID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotChatID", reflect.TypeOf((*MockLeftChatMembersMessage)(nil).BotChatID))
}

// LeftChatMembers mocks base method.
func (m *MockLeftChatMembersMessage) LeftChatMembers() []botinput.Actor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeftChatMembers")
	ret0, _ := ret[0].([]botinput.Actor)
	return ret0
}

// LeftChatMembers indicates an expected call of LeftChatMembers.
func (mr *MockLeftChatMembersMessageMockRecorder) LeftChatMembers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeftChatMembers", reflect.TypeOf((*MockLeftChatMembersMessage)(nil).LeftChatMembers))
}
