// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: NewChatMembersMessage)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput NewChatMembersMessage
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookNewChatMembersMessage is a mock of NewChatMembersMessage interface.
type MockWebhookNewChatMembersMessage struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookNewChatMembersMessageMockRecorder
	isgomock struct{}
}

// MockWebhookNewChatMembersMessageMockRecorder is the mock recorder for MockWebhookNewChatMembersMessage.
type MockWebhookNewChatMembersMessageMockRecorder struct {
	mock *MockWebhookNewChatMembersMessage
}

// NewMockWebhookNewChatMembersMessage creates a new mock instance.
func NewMockWebhookNewChatMembersMessage(ctrl *gomock.Controller) *MockWebhookNewChatMembersMessage {
	mock := &MockWebhookNewChatMembersMessage{ctrl: ctrl}
	mock.recorder = &MockWebhookNewChatMembersMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookNewChatMembersMessage) EXPECT() *MockWebhookNewChatMembersMessageMockRecorder {
	return m.recorder
}

// BotChatID mocks base method.
func (m *MockWebhookNewChatMembersMessage) BotChatID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotChatID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BotChatID indicates an expected call of BotChatID.
func (mr *MockWebhookNewChatMembersMessageMockRecorder) BotChatID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotChatID", reflect.TypeOf((*MockWebhookNewChatMembersMessage)(nil).BotChatID))
}

// NewChatMembers mocks base method.
func (m *MockWebhookNewChatMembersMessage) NewChatMembers() []botinput.Actor {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewChatMembers")
	ret0, _ := ret[0].([]botinput.Actor)
	return ret0
}

// NewChatMembers indicates an expected call of NewChatMembers.
func (mr *MockWebhookNewChatMembersMessageMockRecorder) NewChatMembers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewChatMembers", reflect.TypeOf((*MockWebhookNewChatMembersMessage)(nil).NewChatMembers))
}
