// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: WebhookChat)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput WebhookChat
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWebhookChat is a mock of WebhookChat interface.
type MockWebhookChat struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookChatMockRecorder
	isgomock struct{}
}

// MockWebhookChatMockRecorder is the mock recorder for MockWebhookChat.
type MockWebhookChatMockRecorder struct {
	mock *MockWebhookChat
}

// NewMockWebhookChat creates a new mock instance.
func NewMockWebhookChat(ctrl *gomock.Controller) *MockWebhookChat {
	mock := &MockWebhookChat{ctrl: ctrl}
	mock.recorder = &MockWebhookChatMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookChat) EXPECT() *MockWebhookChatMockRecorder {
	return m.recorder
}

// GetID mocks base method.
func (m *MockWebhookChat) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockWebhookChatMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockWebhookChat)(nil).GetID))
}

// GetType mocks base method.
func (m *MockWebhookChat) GetType() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetType")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetType indicates an expected call of GetType.
func (mr *MockWebhookChatMockRecorder) GetType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetType", reflect.TypeOf((*MockWebhookChat)(nil).GetType))
}

// IsGroupChat mocks base method.
func (m *MockWebhookChat) IsGroupChat() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsGroupChat")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsGroupChat indicates an expected call of IsGroupChat.
func (mr *MockWebhookChatMockRecorder) IsGroupChat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsGroupChat", reflect.TypeOf((*MockWebhookChat)(nil).IsGroupChat))
}
