// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: WebhookSharedUsersMessage)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput WebhookSharedUsersMessage
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"
	time "time"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookSharedUsersMessage is a mock of WebhookSharedUsersMessage interface.
type MockWebhookSharedUsersMessage struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookSharedUsersMessageMockRecorder
	isgomock struct{}
}

// MockWebhookSharedUsersMessageMockRecorder is the mock recorder for MockWebhookSharedUsersMessage.
type MockWebhookSharedUsersMessageMockRecorder struct {
	mock *MockWebhookSharedUsersMessage
}

// NewMockWebhookSharedUsersMessage creates a new mock instance.
func NewMockWebhookSharedUsersMessage(ctrl *gomock.Controller) *MockWebhookSharedUsersMessage {
	mock := &MockWebhookSharedUsersMessage{ctrl: ctrl}
	mock.recorder = &MockWebhookSharedUsersMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookSharedUsersMessage) EXPECT() *MockWebhookSharedUsersMessageMockRecorder {
	return m.recorder
}

// BotChatID mocks base method.
func (m *MockWebhookSharedUsersMessage) BotChatID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotChatID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BotChatID indicates an expected call of BotChatID.
func (mr *MockWebhookSharedUsersMessageMockRecorder) BotChatID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotChatID", reflect.TypeOf((*MockWebhookSharedUsersMessage)(nil).BotChatID))
}

// Chat mocks base method.
func (m *MockWebhookSharedUsersMessage) Chat() botinput.Chat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat")
	ret0, _ := ret[0].(botinput.Chat)
	return ret0
}

// Chat indicates an expected call of Chat.
func (mr *MockWebhookSharedUsersMessageMockRecorder) Chat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockWebhookSharedUsersMessage)(nil).Chat))
}

// GetRecipient mocks base method.
func (m *MockWebhookSharedUsersMessage) GetRecipient() botinput.Recipient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipient")
	ret0, _ := ret[0].(botinput.Recipient)
	return ret0
}

// GetRecipient indicates an expected call of GetRecipient.
func (mr *MockWebhookSharedUsersMessageMockRecorder) GetRecipient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipient", reflect.TypeOf((*MockWebhookSharedUsersMessage)(nil).GetRecipient))
}

// GetRequestID mocks base method.
func (m *MockWebhookSharedUsersMessage) GetRequestID() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestID")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetRequestID indicates an expected call of GetRequestID.
func (mr *MockWebhookSharedUsersMessageMockRecorder) GetRequestID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestID", reflect.TypeOf((*MockWebhookSharedUsersMessage)(nil).GetRequestID))
}

// GetSender mocks base method.
func (m *MockWebhookSharedUsersMessage) GetSender() botinput.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSender")
	ret0, _ := ret[0].(botinput.User)
	return ret0
}

// GetSender indicates an expected call of GetSender.
func (mr *MockWebhookSharedUsersMessageMockRecorder) GetSender() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSender", reflect.TypeOf((*MockWebhookSharedUsersMessage)(nil).GetSender))
}

// GetSharedUsers mocks base method.
func (m *MockWebhookSharedUsersMessage) GetSharedUsers() []botinput.SharedUserMessageItem {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSharedUsers")
	ret0, _ := ret[0].([]botinput.SharedUserMessageItem)
	return ret0
}

// GetSharedUsers indicates an expected call of GetSharedUsers.
func (mr *MockWebhookSharedUsersMessageMockRecorder) GetSharedUsers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSharedUsers", reflect.TypeOf((*MockWebhookSharedUsersMessage)(nil).GetSharedUsers))
}

// GetTime mocks base method.
func (m *MockWebhookSharedUsersMessage) GetTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetTime indicates an expected call of GetTime.
func (mr *MockWebhookSharedUsersMessageMockRecorder) GetTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTime", reflect.TypeOf((*MockWebhookSharedUsersMessage)(nil).GetTime))
}

// InputType mocks base method.
func (m *MockWebhookSharedUsersMessage) InputType() botinput.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputType")
	ret0, _ := ret[0].(botinput.Type)
	return ret0
}

// InputType indicates an expected call of InputType.
func (mr *MockWebhookSharedUsersMessageMockRecorder) InputType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputType", reflect.TypeOf((*MockWebhookSharedUsersMessage)(nil).InputType))
}

// IntID mocks base method.
func (m *MockWebhookSharedUsersMessage) IntID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// IntID indicates an expected call of IntID.
func (mr *MockWebhookSharedUsersMessageMockRecorder) IntID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntID", reflect.TypeOf((*MockWebhookSharedUsersMessage)(nil).IntID))
}

// LogRequest mocks base method.
func (m *MockWebhookSharedUsersMessage) LogRequest() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogRequest")
}

// LogRequest indicates an expected call of LogRequest.
func (mr *MockWebhookSharedUsersMessageMockRecorder) LogRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogRequest", reflect.TypeOf((*MockWebhookSharedUsersMessage)(nil).LogRequest))
}

// StringID mocks base method.
func (m *MockWebhookSharedUsersMessage) StringID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringID")
	ret0, _ := ret[0].(string)
	return ret0
}

// StringID indicates an expected call of StringID.
func (mr *MockWebhookSharedUsersMessageMockRecorder) StringID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringID", reflect.TypeOf((*MockWebhookSharedUsersMessage)(nil).StringID))
}
