// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: PhotoMessage)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput PhotoMessage
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"
	time "time"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookPhotoMessage is a mock of PhotoMessage interface.
type MockWebhookPhotoMessage struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookPhotoMessageMockRecorder
	isgomock struct{}
}

// MockWebhookPhotoMessageMockRecorder is the mock recorder for MockWebhookPhotoMessage.
type MockWebhookPhotoMessageMockRecorder struct {
	mock *MockWebhookPhotoMessage
}

// NewMockWebhookPhotoMessage creates a new mock instance.
func NewMockWebhookPhotoMessage(ctrl *gomock.Controller) *MockWebhookPhotoMessage {
	mock := &MockWebhookPhotoMessage{ctrl: ctrl}
	mock.recorder = &MockWebhookPhotoMessageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookPhotoMessage) EXPECT() *MockWebhookPhotoMessageMockRecorder {
	return m.recorder
}

// BotChatID mocks base method.
func (m *MockWebhookPhotoMessage) BotChatID() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotChatID")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BotChatID indicates an expected call of BotChatID.
func (mr *MockWebhookPhotoMessageMockRecorder) BotChatID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotChatID", reflect.TypeOf((*MockWebhookPhotoMessage)(nil).BotChatID))
}

// Chat mocks base method.
func (m *MockWebhookPhotoMessage) Chat() botinput.Chat {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat")
	ret0, _ := ret[0].(botinput.Chat)
	return ret0
}

// Chat indicates an expected call of Chat.
func (mr *MockWebhookPhotoMessageMockRecorder) Chat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockWebhookPhotoMessage)(nil).Chat))
}

// GetRecipient mocks base method.
func (m *MockWebhookPhotoMessage) GetRecipient() botinput.Recipient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecipient")
	ret0, _ := ret[0].(botinput.Recipient)
	return ret0
}

// GetRecipient indicates an expected call of GetRecipient.
func (mr *MockWebhookPhotoMessageMockRecorder) GetRecipient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecipient", reflect.TypeOf((*MockWebhookPhotoMessage)(nil).GetRecipient))
}

// GetSender mocks base method.
func (m *MockWebhookPhotoMessage) GetSender() botinput.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSender")
	ret0, _ := ret[0].(botinput.User)
	return ret0
}

// GetSender indicates an expected call of GetSender.
func (mr *MockWebhookPhotoMessageMockRecorder) GetSender() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSender", reflect.TypeOf((*MockWebhookPhotoMessage)(nil).GetSender))
}

// GetTime mocks base method.
func (m *MockWebhookPhotoMessage) GetTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetTime indicates an expected call of GetTime.
func (mr *MockWebhookPhotoMessageMockRecorder) GetTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTime", reflect.TypeOf((*MockWebhookPhotoMessage)(nil).GetTime))
}

// InputType mocks base method.
func (m *MockWebhookPhotoMessage) InputType() botinput.Type {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputType")
	ret0, _ := ret[0].(botinput.Type)
	return ret0
}

// InputType indicates an expected call of InputType.
func (mr *MockWebhookPhotoMessageMockRecorder) InputType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputType", reflect.TypeOf((*MockWebhookPhotoMessage)(nil).InputType))
}

// IntID mocks base method.
func (m *MockWebhookPhotoMessage) IntID() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntID")
	ret0, _ := ret[0].(int64)
	return ret0
}

// IntID indicates an expected call of IntID.
func (mr *MockWebhookPhotoMessageMockRecorder) IntID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntID", reflect.TypeOf((*MockWebhookPhotoMessage)(nil).IntID))
}

// LogRequest mocks base method.
func (m *MockWebhookPhotoMessage) LogRequest() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogRequest")
}

// LogRequest indicates an expected call of LogRequest.
func (mr *MockWebhookPhotoMessageMockRecorder) LogRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogRequest", reflect.TypeOf((*MockWebhookPhotoMessage)(nil).LogRequest))
}

// StringID mocks base method.
func (m *MockWebhookPhotoMessage) StringID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StringID")
	ret0, _ := ret[0].(string)
	return ret0
}

// StringID indicates an expected call of StringID.
func (mr *MockWebhookPhotoMessageMockRecorder) StringID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StringID", reflect.TypeOf((*MockWebhookPhotoMessage)(nil).StringID))
}
