// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: WebhookRecipient)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput WebhookRecipient
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWebhookRecipient is a mock of WebhookRecipient interface.
type MockWebhookRecipient struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookRecipientMockRecorder
	isgomock struct{}
}

// MockWebhookRecipientMockRecorder is the mock recorder for MockWebhookRecipient.
type MockWebhookRecipientMockRecorder struct {
	mock *MockWebhookRecipient
}

// NewMockWebhookRecipient creates a new mock instance.
func NewMockWebhookRecipient(ctrl *gomock.Controller) *MockWebhookRecipient {
	mock := &MockWebhookRecipient{ctrl: ctrl}
	mock.recorder = &MockWebhookRecipientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookRecipient) EXPECT() *MockWebhookRecipientMockRecorder {
	return m.recorder
}

// GetFirstName mocks base method.
func (m *MockWebhookRecipient) GetFirstName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFirstName indicates an expected call of GetFirstName.
func (mr *MockWebhookRecipientMockRecorder) GetFirstName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstName", reflect.TypeOf((*MockWebhookRecipient)(nil).GetFirstName))
}

// GetID mocks base method.
func (m *MockWebhookRecipient) GetID() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(any)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockWebhookRecipientMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockWebhookRecipient)(nil).GetID))
}

// GetLanguage mocks base method.
func (m *MockWebhookRecipient) GetLanguage() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLanguage")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLanguage indicates an expected call of GetLanguage.
func (mr *MockWebhookRecipientMockRecorder) GetLanguage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLanguage", reflect.TypeOf((*MockWebhookRecipient)(nil).GetLanguage))
}

// GetLastName mocks base method.
func (m *MockWebhookRecipient) GetLastName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLastName indicates an expected call of GetLastName.
func (mr *MockWebhookRecipientMockRecorder) GetLastName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastName", reflect.TypeOf((*MockWebhookRecipient)(nil).GetLastName))
}

// GetUserName mocks base method.
func (m *MockWebhookRecipient) GetUserName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserName indicates an expected call of GetUserName.
func (mr *MockWebhookRecipientMockRecorder) GetUserName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserName", reflect.TypeOf((*MockWebhookRecipient)(nil).GetUserName))
}

// IsBotUser mocks base method.
func (m *MockWebhookRecipient) IsBotUser() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBotUser")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBotUser indicates an expected call of IsBotUser.
func (mr *MockWebhookRecipientMockRecorder) IsBotUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBotUser", reflect.TypeOf((*MockWebhookRecipient)(nil).IsBotUser))
}

// Platform mocks base method.
func (m *MockWebhookRecipient) Platform() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Platform")
	ret0, _ := ret[0].(string)
	return ret0
}

// Platform indicates an expected call of Platform.
func (mr *MockWebhookRecipientMockRecorder) Platform() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Platform", reflect.TypeOf((*MockWebhookRecipient)(nil).Platform))
}
