// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: WebhookSender)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput WebhookSender
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWebhookSender is a mock of WebhookSender interface.
type MockWebhookSender struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookSenderMockRecorder
	isgomock struct{}
}

// MockWebhookSenderMockRecorder is the mock recorder for MockWebhookSender.
type MockWebhookSenderMockRecorder struct {
	mock *MockWebhookSender
}

// NewMockWebhookSender creates a new mock instance.
func NewMockWebhookSender(ctrl *gomock.Controller) *MockWebhookSender {
	mock := &MockWebhookSender{ctrl: ctrl}
	mock.recorder = &MockWebhookSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookSender) EXPECT() *MockWebhookSenderMockRecorder {
	return m.recorder
}

// GetAvatar mocks base method.
func (m *MockWebhookSender) GetAvatar() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatar")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAvatar indicates an expected call of GetAvatar.
func (mr *MockWebhookSenderMockRecorder) GetAvatar() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatar", reflect.TypeOf((*MockWebhookSender)(nil).GetAvatar))
}

// GetFirstName mocks base method.
func (m *MockWebhookSender) GetFirstName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFirstName indicates an expected call of GetFirstName.
func (mr *MockWebhookSenderMockRecorder) GetFirstName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstName", reflect.TypeOf((*MockWebhookSender)(nil).GetFirstName))
}

// GetID mocks base method.
func (m *MockWebhookSender) GetID() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(any)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockWebhookSenderMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockWebhookSender)(nil).GetID))
}

// GetLanguage mocks base method.
func (m *MockWebhookSender) GetLanguage() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLanguage")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLanguage indicates an expected call of GetLanguage.
func (mr *MockWebhookSenderMockRecorder) GetLanguage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLanguage", reflect.TypeOf((*MockWebhookSender)(nil).GetLanguage))
}

// GetLastName mocks base method.
func (m *MockWebhookSender) GetLastName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLastName indicates an expected call of GetLastName.
func (mr *MockWebhookSenderMockRecorder) GetLastName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastName", reflect.TypeOf((*MockWebhookSender)(nil).GetLastName))
}

// GetUserName mocks base method.
func (m *MockWebhookSender) GetUserName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserName indicates an expected call of GetUserName.
func (mr *MockWebhookSenderMockRecorder) GetUserName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserName", reflect.TypeOf((*MockWebhookSender)(nil).GetUserName))
}

// IsBotUser mocks base method.
func (m *MockWebhookSender) IsBotUser() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBotUser")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBotUser indicates an expected call of IsBotUser.
func (mr *MockWebhookSenderMockRecorder) IsBotUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBotUser", reflect.TypeOf((*MockWebhookSender)(nil).IsBotUser))
}

// Platform mocks base method.
func (m *MockWebhookSender) Platform() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Platform")
	ret0, _ := ret[0].(string)
	return ret0
}

// Platform indicates an expected call of Platform.
func (mr *MockWebhookSenderMockRecorder) Platform() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Platform", reflect.TypeOf((*MockWebhookSender)(nil).Platform))
}
