// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botinput (interfaces: WebhookActor)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botinput WebhookActor
//

// Package mock_botinput is a generated GoMock package.
package mock_botinput

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWebhookActor is a mock of WebhookActor interface.
type MockWebhookActor struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookActorMockRecorder
	isgomock struct{}
}

// MockWebhookActorMockRecorder is the mock recorder for MockWebhookActor.
type MockWebhookActorMockRecorder struct {
	mock *MockWebhookActor
}

// NewMockWebhookActor creates a new mock instance.
func NewMockWebhookActor(ctrl *gomock.Controller) *MockWebhookActor {
	mock := &MockWebhookActor{ctrl: ctrl}
	mock.recorder = &MockWebhookActorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookActor) EXPECT() *MockWebhookActorMockRecorder {
	return m.recorder
}

// GetFirstName mocks base method.
func (m *MockWebhookActor) GetFirstName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirstName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetFirstName indicates an expected call of GetFirstName.
func (mr *MockWebhookActorMockRecorder) GetFirstName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirstName", reflect.TypeOf((*MockWebhookActor)(nil).GetFirstName))
}

// GetID mocks base method.
func (m *MockWebhookActor) GetID() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(any)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockWebhookActorMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockWebhookActor)(nil).GetID))
}

// GetLanguage mocks base method.
func (m *MockWebhookActor) GetLanguage() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLanguage")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLanguage indicates an expected call of GetLanguage.
func (mr *MockWebhookActorMockRecorder) GetLanguage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLanguage", reflect.TypeOf((*MockWebhookActor)(nil).GetLanguage))
}

// GetLastName mocks base method.
func (m *MockWebhookActor) GetLastName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetLastName indicates an expected call of GetLastName.
func (mr *MockWebhookActorMockRecorder) GetLastName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastName", reflect.TypeOf((*MockWebhookActor)(nil).GetLastName))
}

// GetUserName mocks base method.
func (m *MockWebhookActor) GetUserName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserName indicates an expected call of GetUserName.
func (mr *MockWebhookActorMockRecorder) GetUserName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserName", reflect.TypeOf((*MockWebhookActor)(nil).GetUserName))
}

// IsBotUser mocks base method.
func (m *MockWebhookActor) IsBotUser() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBotUser")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsBotUser indicates an expected call of IsBotUser.
func (mr *MockWebhookActorMockRecorder) IsBotUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBotUser", reflect.TypeOf((*MockWebhookActor)(nil).IsBotUser))
}

// Platform mocks base method.
func (m *MockWebhookActor) Platform() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Platform")
	ret0, _ := ret[0].(string)
	return ret0
}

// Platform indicates an expected call of Platform.
func (mr *MockWebhookActorMockRecorder) Platform() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Platform", reflect.TypeOf((*MockWebhookActor)(nil).Platform))
}
