// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botmsg (interfaces: Attachment)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botmsg Attachment
//

// Package mock_botmsg is a generated GoMock package.
package mock_botmsg

import (
	reflect "reflect"

	botmsg "github.com/bots-go-framework/bots-fw/botmsg"
	gomock "go.uber.org/mock/gomock"
)

// MockAttachment is a mock of Attachment interface.
type MockAttachment struct {
	ctrl     *gomock.Controller
	recorder *MockAttachmentMockRecorder
	isgomock struct{}
}

// MockAttachmentMockRecorder is the mock recorder for MockAttachment.
type MockAttachmentMockRecorder struct {
	mock *MockAttachment
}

// NewMockAttachment creates a new mock instance.
func NewMockAttachment(ctrl *gomock.Controller) *MockAttachment {
	mock := &MockAttachment{ctrl: ctrl}
	mock.recorder = &MockAttachmentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAttachment) EXPECT() *MockAttachmentMockRecorder {
	return m.recorder
}

// AttachmentType mocks base method.
func (m *MockAttachment) AttachmentType() botmsg.AttachmentType {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachmentType")
	ret0, _ := ret[0].(botmsg.AttachmentType)
	return ret0
}

// AttachmentType indicates an expected call of AttachmentType.
func (mr *MockAttachmentMockRecorder) AttachmentType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachmentType", reflect.TypeOf((*MockAttachment)(nil).AttachmentType))
}
