// Code generated by "stringer -type=WebhookInputType"; DO NOT EDIT.

package botinput

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[WebhookInputUnknown-0]
	_ = x[WebhookInputNotImplemented-1]
	_ = x[WebhookInputText-2]
	_ = x[WebhookInputVoice-3]
	_ = x[WebhookInputPhoto-4]
	_ = x[WebhookInputAudio-5]
	_ = x[WebhookInputContact-6]
	_ = x[WebhookInputPostback-7]
	_ = x[WebhookInputDelivery-8]
	_ = x[WebhookInputAttachment-9]
	_ = x[WebhookInputInlineQuery-10]
	_ = x[WebhookInputCallbackQuery-11]
	_ = x[WebhookInputReferral-12]
	_ = x[WebhookInputChosenInlineResult-13]
	_ = x[WebhookInputSubscribed-14]
	_ = x[WebhookInputUnsubscribed-15]
	_ = x[WebhookInputConversationStarted-16]
	_ = x[WebhookInputNewChatMembers-17]
	_ = x[WebhookInputLeftChatMembers-18]
	_ = x[WebhookInputSticker-19]
	_ = x[WebhookInputSharedUsers-20]
	_ = x[WebhookInputPreCheckoutQuery-21]
	_ = x[WebhookInputSuccessfulPayment-22]
	_ = x[WebhookInputRefundedPayment-23]
}

const _WebhookInputType_name = "WebhookInputUnknownWebhookInputNotImplementedWebhookInputTextWebhookInputVoiceWebhookInputPhotoWebhookInputAudioWebhookInputContactWebhookInputPostbackWebhookInputDeliveryWebhookInputAttachmentWebhookInputInlineQueryWebhookInputCallbackQueryWebhookInputReferralWebhookInputChosenInlineResultWebhookInputSubscribedWebhookInputUnsubscribedWebhookInputConversationStartedWebhookInputNewChatMembersWebhookInputLeftChatMembersWebhookInputStickerWebhookInputSharedUsersWebhookInputPreCheckoutQueryWebhookInputSuccessfulPaymentWebhookInputRefundedPayment"

var _WebhookInputType_index = [...]uint16{0, 19, 45, 61, 78, 95, 112, 131, 151, 171, 193, 216, 241, 261, 291, 313, 337, 368, 394, 421, 440, 463, 491, 520, 547}

func (i WebhookInputType) String() string {
	if i < 0 || i >= WebhookInputType(len(_WebhookInputType_index)-1) {
		return "WebhookInputType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _WebhookInputType_name[_WebhookInputType_index[i]:_WebhookInputType_index[i+1]]
}
