// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botsfw (interfaces: WebhookRequestContext)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botsfw WebhookRequestContext
//

// Package mock_botsfw is a generated GoMock package.
package mock_botsfw

import (
	context "context"
	http "net/http"
	reflect "reflect"

	botsfw "github.com/bots-go-framework/bots-fw/botsfw"
	dal "github.com/dal-go/dalgo/dal"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookRequestContext is a mock of WebhookRequestContext interface.
type MockWebhookRequestContext struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookRequestContextMockRecorder
	isgomock struct{}
}

// MockWebhookRequestContextMockRecorder is the mock recorder for MockWebhookRequestContext.
type MockWebhookRequestContextMockRecorder struct {
	mock *MockWebhookRequestContext
}

// NewMockWebhookRequestContext creates a new mock instance.
func NewMockWebhookRequestContext(ctrl *gomock.Controller) *MockWebhookRequestContext {
	mock := &MockWebhookRequestContext{ctrl: ctrl}
	mock.recorder = &MockWebhookRequestContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookRequestContext) EXPECT() *MockWebhookRequestContextMockRecorder {
	return m.recorder
}

// AppContext mocks base method.
func (m *MockWebhookRequestContext) AppContext() botsfw.AppContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppContext")
	ret0, _ := ret[0].(botsfw.AppContext)
	return ret0
}

// AppContext indicates an expected call of AppContext.
func (mr *MockWebhookRequestContextMockRecorder) AppContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppContext", reflect.TypeOf((*MockWebhookRequestContext)(nil).AppContext))
}

// BotContext mocks base method.
func (m *MockWebhookRequestContext) BotContext() botsfw.BotContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotContext")
	ret0, _ := ret[0].(botsfw.BotContext)
	return ret0
}

// BotContext indicates an expected call of BotContext.
func (mr *MockWebhookRequestContextMockRecorder) BotContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotContext", reflect.TypeOf((*MockWebhookRequestContext)(nil).BotContext))
}

// BotPlatform mocks base method.
func (m *MockWebhookRequestContext) BotPlatform() botsfw.BotPlatform {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BotPlatform")
	ret0, _ := ret[0].(botsfw.BotPlatform)
	return ret0
}

// BotPlatform indicates an expected call of BotPlatform.
func (mr *MockWebhookRequestContextMockRecorder) BotPlatform() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BotPlatform", reflect.TypeOf((*MockWebhookRequestContext)(nil).BotPlatform))
}

// Context mocks base method.
func (m *MockWebhookRequestContext) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockWebhookRequestContextMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockWebhookRequestContext)(nil).Context))
}

// DB mocks base method.
func (m *MockWebhookRequestContext) DB() dal.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DB")
	ret0, _ := ret[0].(dal.DB)
	return ret0
}

// DB indicates an expected call of DB.
func (mr *MockWebhookRequestContextMockRecorder) DB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DB", reflect.TypeOf((*MockWebhookRequestContext)(nil).DB))
}

// Environment mocks base method.
func (m *MockWebhookRequestContext) Environment() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Environment")
	ret0, _ := ret[0].(string)
	return ret0
}

// Environment indicates an expected call of Environment.
func (mr *MockWebhookRequestContextMockRecorder) Environment() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Environment", reflect.TypeOf((*MockWebhookRequestContext)(nil).Environment))
}

// ExecutionContext mocks base method.
func (m *MockWebhookRequestContext) ExecutionContext() botsfw.ExecutionContext {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecutionContext")
	ret0, _ := ret[0].(botsfw.ExecutionContext)
	return ret0
}

// ExecutionContext indicates an expected call of ExecutionContext.
func (mr *MockWebhookRequestContextMockRecorder) ExecutionContext() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecutionContext", reflect.TypeOf((*MockWebhookRequestContext)(nil).ExecutionContext))
}

// GetBotCode mocks base method.
func (m *MockWebhookRequestContext) GetBotCode() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBotCode")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBotCode indicates an expected call of GetBotCode.
func (mr *MockWebhookRequestContextMockRecorder) GetBotCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBotCode", reflect.TypeOf((*MockWebhookRequestContext)(nil).GetBotCode))
}

// GetBotSettings mocks base method.
func (m *MockWebhookRequestContext) GetBotSettings() *botsfw.BotSettings {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBotSettings")
	ret0, _ := ret[0].(*botsfw.BotSettings)
	return ret0
}

// GetBotSettings indicates an expected call of GetBotSettings.
func (mr *MockWebhookRequestContextMockRecorder) GetBotSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBotSettings", reflect.TypeOf((*MockWebhookRequestContext)(nil).GetBotSettings))
}

// Request mocks base method.
func (m *MockWebhookRequestContext) Request() *http.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request")
	ret0, _ := ret[0].(*http.Request)
	return ret0
}

// Request indicates an expected call of Request.
func (mr *MockWebhookRequestContextMockRecorder) Request() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockWebhookRequestContext)(nil).Request))
}

// SetContext mocks base method.
func (m *MockWebhookRequestContext) SetContext(c context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetContext", c)
}

// SetContext indicates an expected call of SetContext.
func (mr *MockWebhookRequestContextMockRecorder) SetContext(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContext", reflect.TypeOf((*MockWebhookRequestContext)(nil).SetContext), c)
}
