// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botsfw (interfaces: WebhookTelemetry)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botsfw WebhookTelemetry
//

// Package mock_botsfw is a generated GoMock package.
package mock_botsfw

import (
	reflect "reflect"

	botsfw "github.com/bots-go-framework/bots-fw/botsfw"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookTelemetry is a mock of WebhookTelemetry interface.
type MockWebhookTelemetry struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookTelemetryMockRecorder
	isgomock struct{}
}

// MockWebhookTelemetryMockRecorder is the mock recorder for MockWebhookTelemetry.
type MockWebhookTelemetryMockRecorder struct {
	mock *MockWebhookTelemetry
}

// NewMockWebhookTelemetry creates a new mock instance.
func NewMockWebhookTelemetry(ctrl *gomock.Controller) *MockWebhookTelemetry {
	mock := &MockWebhookTelemetry{ctrl: ctrl}
	mock.recorder = &MockWebhookTelemetryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookTelemetry) EXPECT() *MockWebhookTelemetryMockRecorder {
	return m.recorder
}

// Analytics mocks base method.
func (m *MockWebhookTelemetry) Analytics() botsfw.WebhookAnalytics {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Analytics")
	ret0, _ := ret[0].(botsfw.WebhookAnalytics)
	return ret0
}

// Analytics indicates an expected call of Analytics.
func (mr *MockWebhookTelemetryMockRecorder) Analytics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Analytics", reflect.TypeOf((*MockWebhookTelemetry)(nil).Analytics))
}
