// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botsfw (interfaces: WebhookHandler)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botsfw WebhookHandler
//

// Package mock_botsfw is a generated GoMock package.
package mock_botsfw

import (
	context "context"
	http "net/http"
	reflect "reflect"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	botmsg "github.com/bots-go-framework/bots-fw/botmsg"
	botsfw "github.com/bots-go-framework/bots-fw/botsfw"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookHandler is a mock of WebhookHandler interface.
type MockWebhookHandler struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookHandlerMockRecorder
	isgomock struct{}
}

// MockWebhookHandlerMockRecorder is the mock recorder for MockWebhookHandler.
type MockWebhookHandlerMockRecorder struct {
	mock *MockWebhookHandler
}

// NewMockWebhookHandler creates a new mock instance.
func NewMockWebhookHandler(ctrl *gomock.Controller) *MockWebhookHandler {
	mock := &MockWebhookHandler{ctrl: ctrl}
	mock.recorder = &MockWebhookHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookHandler) EXPECT() *MockWebhookHandlerMockRecorder {
	return m.recorder
}

// CreateWebhookContext mocks base method.
func (m *MockWebhookHandler) CreateWebhookContext(args botsfw.CreateWebhookContextArgs) (botsfw.WebhookContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWebhookContext", args)
	ret0, _ := ret[0].(botsfw.WebhookContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWebhookContext indicates an expected call of CreateWebhookContext.
func (mr *MockWebhookHandlerMockRecorder) CreateWebhookContext(args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWebhookContext", reflect.TypeOf((*MockWebhookHandler)(nil).CreateWebhookContext), args)
}

// GetBotContextAndInputs mocks base method.
func (m *MockWebhookHandler) GetBotContextAndInputs(c context.Context, r *http.Request) (*botsfw.BotContext, []botinput.EntryInputs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBotContextAndInputs", c, r)
	ret0, _ := ret[0].(*botsfw.BotContext)
	ret1, _ := ret[1].([]botinput.EntryInputs)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBotContextAndInputs indicates an expected call of GetBotContextAndInputs.
func (mr *MockWebhookHandlerMockRecorder) GetBotContextAndInputs(c, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBotContextAndInputs", reflect.TypeOf((*MockWebhookHandler)(nil).GetBotContextAndInputs), c, r)
}

// GetResponder mocks base method.
func (m *MockWebhookHandler) GetResponder(w http.ResponseWriter, whc botsfw.WebhookContext) botsfw.WebhookResponder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResponder", w, whc)
	ret0, _ := ret[0].(botsfw.WebhookResponder)
	return ret0
}

// GetResponder indicates an expected call of GetResponder.
func (mr *MockWebhookHandlerMockRecorder) GetResponder(w, whc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponder", reflect.TypeOf((*MockWebhookHandler)(nil).GetResponder), w, whc)
}

// HandleUnmatched mocks base method.
func (m *MockWebhookHandler) HandleUnmatched(whc botsfw.WebhookContext) botmsg.MessageFromBot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleUnmatched", whc)
	ret0, _ := ret[0].(botmsg.MessageFromBot)
	return ret0
}

// HandleUnmatched indicates an expected call of HandleUnmatched.
func (mr *MockWebhookHandlerMockRecorder) HandleUnmatched(whc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleUnmatched", reflect.TypeOf((*MockWebhookHandler)(nil).HandleUnmatched), whc)
}

// HandleWebhookRequest mocks base method.
func (m *MockWebhookHandler) HandleWebhookRequest(w http.ResponseWriter, r *http.Request) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleWebhookRequest", w, r)
}

// HandleWebhookRequest indicates an expected call of HandleWebhookRequest.
func (mr *MockWebhookHandlerMockRecorder) HandleWebhookRequest(w, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleWebhookRequest", reflect.TypeOf((*MockWebhookHandler)(nil).HandleWebhookRequest), w, r)
}

// RegisterHttpHandlers mocks base method.
func (m *MockWebhookHandler) RegisterHttpHandlers(driver botsfw.WebhookDriver, botHost botsfw.BotHost, router botsfw.HttpRouter, pathPrefix string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterHttpHandlers", driver, botHost, router, pathPrefix)
}

// RegisterHttpHandlers indicates an expected call of RegisterHttpHandlers.
func (mr *MockWebhookHandlerMockRecorder) RegisterHttpHandlers(driver, botHost, router, pathPrefix any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterHttpHandlers", reflect.TypeOf((*MockWebhookHandler)(nil).RegisterHttpHandlers), driver, botHost, router, pathPrefix)
}
