// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botsfw (interfaces: WebhookI18n)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botsfw WebhookI18n
//

// Package mock_botsfw is a generated GoMock package.
package mock_botsfw

import (
	reflect "reflect"

	i18n "github.com/strongo/i18n"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookI18n is a mock of WebhookI18n interface.
type MockWebhookI18n struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookI18nMockRecorder
	isgomock struct{}
}

// MockWebhookI18nMockRecorder is the mock recorder for MockWebhookI18n.
type MockWebhookI18nMockRecorder struct {
	mock *MockWebhookI18n
}

// NewMockWebhookI18n creates a new mock instance.
func NewMockWebhookI18n(ctrl *gomock.Controller) *MockWebhookI18n {
	mock := &MockWebhookI18n{ctrl: ctrl}
	mock.recorder = &MockWebhookI18nMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookI18n) EXPECT() *MockWebhookI18nMockRecorder {
	return m.recorder
}

// CommandText mocks base method.
func (m *MockWebhookI18n) CommandText(title, icon string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommandText", title, icon)
	ret0, _ := ret[0].(string)
	return ret0
}

// CommandText indicates an expected call of CommandText.
func (mr *MockWebhookI18nMockRecorder) CommandText(title, icon any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommandText", reflect.TypeOf((*MockWebhookI18n)(nil).CommandText), title, icon)
}

// GetTranslator mocks base method.
func (m *MockWebhookI18n) GetTranslator(locale string) i18n.SingleLocaleTranslator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTranslator", locale)
	ret0, _ := ret[0].(i18n.SingleLocaleTranslator)
	return ret0
}

// GetTranslator indicates an expected call of GetTranslator.
func (mr *MockWebhookI18nMockRecorder) GetTranslator(locale any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTranslator", reflect.TypeOf((*MockWebhookI18n)(nil).GetTranslator), locale)
}

// Locale mocks base method.
func (m *MockWebhookI18n) Locale() i18n.Locale {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Locale")
	ret0, _ := ret[0].(i18n.Locale)
	return ret0
}

// Locale indicates an expected call of Locale.
func (mr *MockWebhookI18nMockRecorder) Locale() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Locale", reflect.TypeOf((*MockWebhookI18n)(nil).Locale))
}

// SetLocale mocks base method.
func (m *MockWebhookI18n) SetLocale(code5 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLocale", code5)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLocale indicates an expected call of SetLocale.
func (mr *MockWebhookI18nMockRecorder) SetLocale(code5 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLocale", reflect.TypeOf((*MockWebhookI18n)(nil).SetLocale), code5)
}

// Translate mocks base method.
func (m *MockWebhookI18n) Translate(key string, args ...any) string {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Translate", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Translate indicates an expected call of Translate.
func (mr *MockWebhookI18nMockRecorder) Translate(key any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Translate", reflect.TypeOf((*MockWebhookI18n)(nil).Translate), varargs...)
}

// TranslateNoWarning mocks base method.
func (m *MockWebhookI18n) TranslateNoWarning(key string, args ...any) string {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "TranslateNoWarning", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// TranslateNoWarning indicates an expected call of TranslateNoWarning.
func (mr *MockWebhookI18nMockRecorder) TranslateNoWarning(key any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranslateNoWarning", reflect.TypeOf((*MockWebhookI18n)(nil).TranslateNoWarning), varargs...)
}

// TranslateWithMap mocks base method.
func (m *MockWebhookI18n) TranslateWithMap(key string, args map[string]string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TranslateWithMap", key, args)
	ret0, _ := ret[0].(string)
	return ret0
}

// TranslateWithMap indicates an expected call of TranslateWithMap.
func (mr *MockWebhookI18nMockRecorder) TranslateWithMap(key, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TranslateWithMap", reflect.TypeOf((*MockWebhookI18n)(nil).TranslateWithMap), key, args)
}
