// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botsfw (interfaces: WebhookInputContext)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botsfw WebhookInputContext
//

// Package mock_botsfw is a generated GoMock package.
package mock_botsfw

import (
	reflect "reflect"

	botinput "github.com/bots-go-framework/bots-fw/botinput"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookInputContext is a mock of WebhookInputContext interface.
type MockWebhookInputContext struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookInputContextMockRecorder
	isgomock struct{}
}

// MockWebhookInputContextMockRecorder is the mock recorder for MockWebhookInputContext.
type MockWebhookInputContextMockRecorder struct {
	mock *MockWebhookInputContext
}

// NewMockWebhookInputContext creates a new mock instance.
func NewMockWebhookInputContext(ctrl *gomock.Controller) *MockWebhookInputContext {
	mock := &MockWebhookInputContext{ctrl: ctrl}
	mock.recorder = &MockWebhookInputContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookInputContext) EXPECT() *MockWebhookInputContextMockRecorder {
	return m.recorder
}

// GetBotUserID mocks base method.
func (m *MockWebhookInputContext) GetBotUserID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBotUserID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBotUserID indicates an expected call of GetBotUserID.
func (mr *MockWebhookInputContextMockRecorder) GetBotUserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBotUserID", reflect.TypeOf((*MockWebhookInputContext)(nil).GetBotUserID))
}

// Input mocks base method.
func (m *MockWebhookInputContext) Input() botinput.InputMessage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Input")
	ret0, _ := ret[0].(botinput.InputMessage)
	return ret0
}

// Input indicates an expected call of Input.
func (mr *MockWebhookInputContextMockRecorder) Input() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Input", reflect.TypeOf((*MockWebhookInputContext)(nil).Input))
}

// IsInGroup mocks base method.
func (m *MockWebhookInputContext) IsInGroup() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInGroup")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsInGroup indicates an expected call of IsInGroup.
func (mr *MockWebhookInputContextMockRecorder) IsInGroup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInGroup", reflect.TypeOf((*MockWebhookInputContext)(nil).IsInGroup))
}

// MustBotChatID mocks base method.
func (m *MockWebhookInputContext) MustBotChatID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MustBotChatID")
	ret0, _ := ret[0].(string)
	return ret0
}

// MustBotChatID indicates an expected call of MustBotChatID.
func (mr *MockWebhookInputContextMockRecorder) MustBotChatID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MustBotChatID", reflect.TypeOf((*MockWebhookInputContext)(nil).MustBotChatID))
}
