// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botsfw (interfaces: WebhookMessaging)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botsfw WebhookMessaging
//

// Package mock_botsfw is a generated GoMock package.
package mock_botsfw

import (
	reflect "reflect"

	botmsg "github.com/bots-go-framework/bots-fw/botmsg"
	botsfw "github.com/bots-go-framework/bots-fw/botsfw"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookMessaging is a mock of WebhookMessaging interface.
type MockWebhookMessaging struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookMessagingMockRecorder
	isgomock struct{}
}

// MockWebhookMessagingMockRecorder is the mock recorder for MockWebhookMessaging.
type MockWebhookMessagingMockRecorder struct {
	mock *MockWebhookMessaging
}

// NewMockWebhookMessaging creates a new mock instance.
func NewMockWebhookMessaging(ctrl *gomock.Controller) *MockWebhookMessaging {
	mock := &MockWebhookMessaging{ctrl: ctrl}
	mock.recorder = &MockWebhookMessagingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookMessaging) EXPECT() *MockWebhookMessagingMockRecorder {
	return m.recorder
}

// NewEditMessage mocks base method.
func (m *MockWebhookMessaging) NewEditMessage(text string, format botmsg.Format) (botmsg.MessageFromBot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewEditMessage", text, format)
	ret0, _ := ret[0].(botmsg.MessageFromBot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewEditMessage indicates an expected call of NewEditMessage.
func (mr *MockWebhookMessagingMockRecorder) NewEditMessage(text, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewEditMessage", reflect.TypeOf((*MockWebhookMessaging)(nil).NewEditMessage), text, format)
}

// NewMessage mocks base method.
func (m *MockWebhookMessaging) NewMessage(text string) botmsg.MessageFromBot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMessage", text)
	ret0, _ := ret[0].(botmsg.MessageFromBot)
	return ret0
}

// NewMessage indicates an expected call of NewMessage.
func (mr *MockWebhookMessagingMockRecorder) NewMessage(text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMessage", reflect.TypeOf((*MockWebhookMessaging)(nil).NewMessage), text)
}

// NewMessageByCode mocks base method.
func (m *MockWebhookMessaging) NewMessageByCode(messageCode string, a ...any) botmsg.MessageFromBot {
	m.ctrl.T.Helper()
	varargs := []any{messageCode}
	for _, a_2 := range a {
		varargs = append(varargs, a_2)
	}
	ret := m.ctrl.Call(m, "NewMessageByCode", varargs...)
	ret0, _ := ret[0].(botmsg.MessageFromBot)
	return ret0
}

// NewMessageByCode indicates an expected call of NewMessageByCode.
func (mr *MockWebhookMessagingMockRecorder) NewMessageByCode(messageCode any, a ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{messageCode}, a...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMessageByCode", reflect.TypeOf((*MockWebhookMessaging)(nil).NewMessageByCode), varargs...)
}

// Responder mocks base method.
func (m *MockWebhookMessaging) Responder() botsfw.WebhookResponder {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Responder")
	ret0, _ := ret[0].(botsfw.WebhookResponder)
	return ret0
}

// Responder indicates an expected call of Responder.
func (mr *MockWebhookMessagingMockRecorder) Responder() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Responder", reflect.TypeOf((*MockWebhookMessaging)(nil).Responder))
}
