// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botsfw (interfaces: WebhookUserData)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botsfw WebhookUserData
//

// Package mock_botsfw is a generated GoMock package.
package mock_botsfw

import (
	reflect "reflect"

	botsfwmodels "github.com/bots-go-framework/bots-fw-store/botsfwmodels"
	botsfwstore "github.com/bots-go-framework/bots-fw-store/botsfwstore"
	botsfw "github.com/bots-go-framework/bots-fw/botsfw"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookUserData is a mock of WebhookUserData interface.
type MockWebhookUserData struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookUserDataMockRecorder
	isgomock struct{}
}

// MockWebhookUserDataMockRecorder is the mock recorder for MockWebhookUserData.
type MockWebhookUserDataMockRecorder struct {
	mock *MockWebhookUserData
}

// NewMockWebhookUserData creates a new mock instance.
func NewMockWebhookUserData(ctrl *gomock.Controller) *MockWebhookUserData {
	mock := &MockWebhookUserData{ctrl: ctrl}
	mock.recorder = &MockWebhookUserDataMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookUserData) EXPECT() *MockWebhookUserDataMockRecorder {
	return m.recorder
}

// AppUserData mocks base method.
func (m *MockWebhookUserData) AppUserData() (botsfwmodels.AppUserData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppUserData")
	ret0, _ := ret[0].(botsfwmodels.AppUserData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AppUserData indicates an expected call of AppUserData.
func (mr *MockWebhookUserDataMockRecorder) AppUserData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppUserData", reflect.TypeOf((*MockWebhookUserData)(nil).AppUserData))
}

// AppUserID mocks base method.
func (m *MockWebhookUserData) AppUserID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppUserID")
	ret0, _ := ret[0].(string)
	return ret0
}

// AppUserID indicates an expected call of AppUserID.
func (mr *MockWebhookUserDataMockRecorder) AppUserID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppUserID", reflect.TypeOf((*MockWebhookUserData)(nil).AppUserID))
}

// ChatData mocks base method.
func (m *MockWebhookUserData) ChatData() botsfwmodels.BotChatData {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatData")
	ret0, _ := ret[0].(botsfwmodels.BotChatData)
	return ret0
}

// ChatData indicates an expected call of ChatData.
func (mr *MockWebhookUserDataMockRecorder) ChatData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatData", reflect.TypeOf((*MockWebhookUserData)(nil).ChatData))
}

// GetBotUser mocks base method.
func (m *MockWebhookUserData) GetBotUser() (botsfwstore.PlatformUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBotUser")
	ret0, _ := ret[0].(botsfwstore.PlatformUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBotUser indicates an expected call of GetBotUser.
func (mr *MockWebhookUserDataMockRecorder) GetBotUser() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBotUser", reflect.TypeOf((*MockWebhookUserData)(nil).GetBotUser))
}

// SetBotUserAccessGranted mocks base method.
func (m *MockWebhookUserData) SetBotUserAccessGranted(value bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetBotUserAccessGranted", value)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetBotUserAccessGranted indicates an expected call of SetBotUserAccessGranted.
func (mr *MockWebhookUserDataMockRecorder) SetBotUserAccessGranted(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBotUserAccessGranted", reflect.TypeOf((*MockWebhookUserData)(nil).SetBotUserAccessGranted), value)
}

// IsNewerThen mocks base method.
func (m *MockWebhookUserData) IsNewerThen(chatEntity botsfwmodels.BotChatData) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsNewerThen", chatEntity)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsNewerThen indicates an expected call of IsNewerThen.
func (mr *MockWebhookUserDataMockRecorder) IsNewerThen(chatEntity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsNewerThen", reflect.TypeOf((*MockWebhookUserData)(nil).IsNewerThen), chatEntity)
}

// RecordsFieldsSetter mocks base method.
func (m *MockWebhookUserData) RecordsFieldsSetter() botsfw.BotRecordsFieldsSetter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordsFieldsSetter")
	ret0, _ := ret[0].(botsfw.BotRecordsFieldsSetter)
	return ret0
}

// RecordsFieldsSetter indicates an expected call of RecordsFieldsSetter.
func (mr *MockWebhookUserDataMockRecorder) RecordsFieldsSetter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordsFieldsSetter", reflect.TypeOf((*MockWebhookUserData)(nil).RecordsFieldsSetter))
}

// SaveBotChat mocks base method.
func (m *MockWebhookUserData) SaveBotChat() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBotChat")
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBotChat indicates an expected call of SaveBotChat.
func (mr *MockWebhookUserDataMockRecorder) SaveBotChat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBotChat", reflect.TypeOf((*MockWebhookUserData)(nil).SaveBotChat))
}

// SetUser mocks base method.
func (m *MockWebhookUserData) SetUser(id string, data botsfwmodels.AppUserData) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUser", id, data)
}

// SetUser indicates an expected call of SetUser.
func (mr *MockWebhookUserDataMockRecorder) SetUser(id, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUser", reflect.TypeOf((*MockWebhookUserData)(nil).SetUser), id, data)
}

// UpdateLastProcessed mocks base method.
func (m *MockWebhookUserData) UpdateLastProcessed(chatEntity botsfwmodels.BotChatData) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastProcessed", chatEntity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastProcessed indicates an expected call of UpdateLastProcessed.
func (mr *MockWebhookUserDataMockRecorder) UpdateLastProcessed(chatEntity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastProcessed", reflect.TypeOf((*MockWebhookUserData)(nil).UpdateLastProcessed), chatEntity)
}
