// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bots-go-framework/bots-fw/botsfw (interfaces: WebhookAnalytics)
//
// Generated by this command:
//
//	mockgen github.com/bots-go-framework/bots-fw/botsfw WebhookAnalytics
//

// Package mock_botsfw is a generated GoMock package.
package mock_botsfw

import (
	reflect "reflect"

	analytics "github.com/strongo/analytics"
	gomock "go.uber.org/mock/gomock"
)

// MockWebhookAnalytics is a mock of WebhookAnalytics interface.
type MockWebhookAnalytics struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookAnalyticsMockRecorder
	isgomock struct{}
}

// MockWebhookAnalyticsMockRecorder is the mock recorder for MockWebhookAnalytics.
type MockWebhookAnalyticsMockRecorder struct {
	mock *MockWebhookAnalytics
}

// NewMockWebhookAnalytics creates a new mock instance.
func NewMockWebhookAnalytics(ctrl *gomock.Controller) *MockWebhookAnalytics {
	mock := &MockWebhookAnalytics{ctrl: ctrl}
	mock.recorder = &MockWebhookAnalyticsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookAnalytics) EXPECT() *MockWebhookAnalyticsMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m *MockWebhookAnalytics) Enqueue(message analytics.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Enqueue", message)
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockWebhookAnalyticsMockRecorder) Enqueue(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockWebhookAnalytics)(nil).Enqueue), message)
}
