name: Lint, Vet, Test & Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.17.0' # The Go version to download (if necessary) and use.

      - name: go get ./...
        run: go get ./...

      - name: Lint
        run: go run golang.org/x/lint/golint ./...

      - name: go vet ./...
        run: go vet ./...

      - name: Test
        run: go test ./...

      - name: go build ./...
        run: go build ./...
